### ISSUE TITLE
Font size for pagination information is not consistent with font size for the rest of the text

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/inspectionreportgenerator#2]
# The problem:

The font size for pagination information ("page 1 of 4") is not consistent / much bigger than the font for the rest of the text

![image](https://user-images.githubusercontent.com/31331637/44705483-5540d880-aad1-11e8-9ff1-3a5edf2e5d81.png)

# Solution:

Use the Same font size for for the footer and the pagination information (reduce the size of the font for pagination information)

**Comment by kiatlim** [comment]
See this for the adjusted overall font size: https://s3-ap-southeast-1.amazonaws.com/dev-media-unee-t/2018-09-03/1535940431.pdf

**Comment by franck-boullier** [comment]
Fixed as seen in @kiatlim link
