### ISSUE TITLE
Remove the text 'Handover of unit - ' from the header of an Inspection Report

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/inspectionreportgenerator#5]
An inspection report can be done for things other than the Handover of a unit.

For instance, it can be done when we need to inspect an equipment in the unit or prepare a quote to do renovations/repairs or assess the damages to a unit after something happened for instance

The text 'Handover of unit' is not necessary/confusing, we should only have the {{ .Report.Name }} there

![image](https://user-images.githubusercontent.com/31331637/44943463-402db780-adf9-11e8-83ab-587b9f9215cd.png)

**Comment by kiatlim** [comment]
@franck-boullier The handover of unit text is removed: https://s3-ap-southeast-1.amazonaws.com/dev-media-unee-t/2018-09-03/1535940431.pdf

**Comment by franck-boullier** [comment]
Fixed in the current master
