### ISSUE TITLE
Printed version of the PDF export is off

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/inspectionreportgenerator#7]
# The problem:

When we are printing the [PDF generated version of an Inspection report](https://s3-ap-southeast-1.amazonaws.com/dev-media-unee-t/2018-09-03/1535972234.pdf), the footer is not displayed as expected.

Tests were done on
- different hp printers
- Using a printer emulator (primo PDF)

Example: scan of a page printed on an HP printer ---> the page number at the bottom of the footer are missing

![image](https://user-images.githubusercontent.com/31331637/45133172-763ab500-b1c6-11e8-9b37-cb8d27d9ca56.png)

**Comment by kaihendry** [comment]
I think this has been fixed with @kiatlim changes. If not, please re-open.
